<?php

namespace Neoan3\Component\Contact;

use Neoan3\Frame\Demo;
use Neoan3\Model\Contact\ContactModel;
use Neoan3\Provider\Model\InitModel;

/**
 * Class ContactController
 * @package Neoan3\Component\Contact
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class ContactController extends Demo{

    /**
    * GET: api.v1/contact
    * GET: api.v1/contact/{id}
    * GET: api.v1/contact?{query-string}
    * @param string|null $id
    * @param array $params
    * @return array
    */
    #[InitModel(ContactModel::class)]
    function getContact(?string $id = null, array $params = []): array
    {
        // Restrict access to logged in users?
        // $this->Auth->restrict();
        // (or without dependency on Demo-Frame: $this->provider['auth']->restrict())
        if($id){
            return ContactModel::get($id);
        }
        return ContactModel::find([]);
    }

    /**
     * POST: api.v1/contact
     * @param $body
     * @return array
     */
    #[InitModel(ContactModel::class)]
    function postContact(array $body): array
    {
        return ContactModel::create($body);
    }
}
