<?php

namespace Neoan3\Component\Testing;

use Neoan3\Frame\Demo;

/**
 * Class TestingController
 * @package Neoan3\Component\Testing
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class TestingController extends Demo{

    /**
    * GET: api.v1/testing
    * GET: api.v1/testing/{id}
    * GET: api.v1/testing?{query-string}
    * @param string|null $id
    * @param array $params
    * @return array
    */
    function getTesting(?string $id = null, array $params = []): array
    {
        return $this->getMeta(['website'=>'https://www.theverge.com']);

    }

    /**
     * POST: api.v1/testing
     * @param $body
     * @return array
     */
    function postTesting(array $body): array
    {
        return $body;
    }
}
