<?php

namespace Neoan3\Component\Contacts;

use Neoan3\Frame\Demo;
use Neoan3\Model\Contact\ContactModel;
use Neoan3\Provider\Model\InitModel;

/**
 * Class ContactsController
 * @package Neoan3\Component\Contacts
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class ContactsController extends Demo{

    /**
    * GET: api.v1/contacts
    * GET: api.v1/contacts/{id}
    * GET: api.v1/contacts?{query-string}
    * @param string|null $id
    * @param array $params
    * @return array
    */
    #[InitModel(ContactModel::class)]
    function getContacts(?string $id = null, array $params = []): array
    {
        // Restrict access to logged in users?
        // $this->Auth->restrict();
        // (or without dependency on Demo-Frame: $this->provider['auth']->restrict())
        if($id){
            // Retrieve a model?
            // return $this->loadModel(\Neoan3\Model\Contacts\ContactsModel::class)::get($id);
        }
        return $params;
    }

    /**
     * POST: api.v1/contacts
     * @param $body
     * @return array
     */
    #[InitModel(ContactModel::class)]
    function postContacts(array $body): array
    {
        return $body;
    }
}
