<?php

namespace Neoan3\Component\Outlets;

use Neoan3\Frame\Demo;
use Neoan3\Model\Contact\ContactModel;
use Neoan3\Model\Outlet\OutletModel;
use Neoan3\Provider\Model\InitModel;

/**
 * Class OutletsController
 * @package Neoan3\Component\Outlets
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class OutletsController extends Demo{

    /**
    * GET: api.v1/outlets
    * GET: api.v1/outlets/{id}
    * GET: api.v1/outlets?{query-string}
    * @param string|null $id
    * @param array $params
    * @return array
    */
    #[InitModel(OutletModel::class)]
    #[InitModel(ContactModel::class)]
    function getOutlets(?string $id = null, array $params = []): array
    {
        $contact = ContactModel::find([])[0];
        $outlet = OutletModel::find([])[0];
        $this->provider['db']->smart('>insert into contact_outlet set outlet_id=unhex({{outlet_id}}), contact_id=unhex({{contact_id}})', ['outlet_id' => $outlet['id'], 'contact_id' => $contact['id']]);
        return $params;
    }

    /**
     * POST: api.v1/outlets
     * @param $body
     * @return array
     */
    #[InitModel(OutletModel::class)]
    function postOutlets(array $body): array
    {
        return OutletModel::create($body);
    }
}
