<?php

namespace Neoan3\Component\Calls;

use Neoan3\Frame\Demo;

/**
 * Class CallsController
 * @package Neoan3\Component\Calls
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class CallsController extends Demo{

    /**
    * GET: api.v1/calls
    * GET: api.v1/calls/{id}
    * GET: api.v1/calls?{query-string}
    * @param string|null $id
    * @param array $params
    * @return array
    */
    function getCalls(?string $id = null, array $params = []): array
    {
        // Restrict access to logged in users?
        // $this->Auth->restrict();
        // (or without dependency on Demo-Frame: $this->provider['auth']->restrict())
        if($id){
            // Retrieve a model?
            // return $this->loadModel(\Neoan3\Model\Calls\CallsModel::class)::get($id);
        }
        return $params;
    }

    /**
     * POST: api.v1/calls
     * @param $body
     * @return array
     */
    function postCalls(array $body): array
    {
        return $body;
    }
}
