<?php

namespace Neoan3\Component\Clients;

use Neoan3\Frame\Demo;

/**
 * Class ClientsController
 * @package Neoan3\Component\Clients
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class ClientsController extends Demo{

    /**
    * GET: api.v1/clients
    * GET: api.v1/clients/{id}
    * GET: api.v1/clients?{query-string}
    * @param string|null $id
    * @param array $params
    * @return array
    */
    function getClients(?string $id = null, array $params = []): array
    {
        // Restrict access to logged in users?
        // $this->Auth->restrict();
        // (or without dependency on Demo-Frame: $this->provider['auth']->restrict())
        if($id){
            // Retrieve a model?
            // return $this->loadModel(\Neoan3\Model\Clients\ClientsModel::class)::get($id);
        }
        return $params;
    }

    /**
     * POST: api.v1/clients
     * @param $body
     * @return array
     */
    function postClients(array $body): array
    {
        return $body;
    }
}
